export const BARS = [
  {
    name: "Football Factory at Legends",
    address: "6 W 33rd St, Midtown, Manhattan",
    borough: "Manhattan", neighborhood: "Midtown", team: "Open",
    tags: ["20+ big screens", "2 floors", "Soccer memorabilia", "Food menu", "Opens 5am for early games"],
    desc: "A two-floor soccer bar with 20+ big-screen TVs and the largest soccer memorabilia collection in the US. Home to over 30 NYC supporter clubs.",
    review: "A sports bar in NYC that will open their doors for the 5am games. The Football Factory at Legends is, well, legendary.",
    reviewSource: "Hudson River Blue, 2022",
  },
  {
    name: "Smithfield Hall",
    address: "138 W 25th St, Chelsea, Manhattan",
    borough: "Manhattan", neighborhood: "Chelsea", team: "England",
    tags: ["29 TVs indoors", "8 outdoor TVs", "Heated outdoor area", "Official Chelsea FC bar"],
    desc: "A self-proclaimed NYC soccer temple with 29 TVs indoors and 8 more outdoors. Official home of the NYC Chelsea supporters club, welcomes all fans.",
    review: "Known for its friendly staff and welcoming environment. Even if you are not a Chelsea fan, you will feel welcome.",
    reviewSource: "NYC Tourism Guide",
  },
  {
    name: "Banter Bar",
    address: "456 Jefferson St, Williamsburg, Brooklyn",
    borough: "Brooklyn", neighborhood: "Williamsburg", team: "Open",
    tags: ["14 flatscreens", "5 outdoor TVs", "Private viewing room", "Soccer memorabilia"],
    desc: "Williamsburg soccer bar streaming every World Cup 2022 match across 14 flatscreens plus 5 outdoor TVs. Private room available for groups.",
    review: "Banter Bar is a staple soccer bar in Williamsburg. Their 'Football Never Sleeps' motto is as evident as it gets.",
    reviewSource: "Secret NYC, 2022",
  },
  {
    name: "Red Lion NYC",
    address: "151 Bleecker St, Greenwich Village, Manhattan",
    borough: "Manhattan", neighborhood: "East Village", team: "Open",
    tags: ["10+ HD screens", "Projection screens", "Team-specific food specials", "Live music nights"],
    desc: "A Greenwich Village institution streaming every game with team-specific food specials. Already calling itself the best bar in NYC to watch the World Cup 2026.",
    review: "The Red Lion is going all out for the World Cup, including streaming every game, doing giveaways, and specialty-crafted dishes focused around different teams.",
    reviewSource: "Secret NYC, 2022",
  },
  {
    name: "Olly Olly Market",
    address: "601 W 26th St, Chelsea, Manhattan",
    borough: "Manhattan", neighborhood: "Chelsea", team: "Open",
    tags: ["17,000 sq ft space", "Projection screens", "Country-specific food specials"],
    desc: "A massive 17,000 sq ft Chelsea market space that hosted World Cup 2022 parties with projection screens and country-specific food and drink specials.",
    review: "Olly Olly Market hosted World Cup viewing parties on projector screens in their 17,000 square foot space with speciality food and beverage specials.",
    reviewSource: "Secret NYC, 2022",
  },
  {
    name: "Monro Pub",
    address: "481 5th Ave, Park Slope, Brooklyn",
    borough: "Brooklyn", neighborhood: "Park Slope", team: "Open",
    tags: ["Multiple screens", "All nations' flags displayed"],
    desc: "A Park Slope bar that transformed into a full World Cup 2022 venue displaying flags of every participating nation, opening early for all group stage matches.",
    review: "A Liverpool FC supporters' bar transformed into a World Cup bar. Flags of each participating nation on display, and plenty of screens.",
    reviewSource: "Hudson River Blue",
  },
  {
    name: "Santo Brúklin",
    address: "348 Court St, Gowanus, Brooklyn",
    borough: "Brooklyn", neighborhood: "Park Slope", team: "Brazil",
    tags: ["Big-screen TV", "Indoor + outdoor", "Caipirinhas", "All-you-can-eat feijoada on Brazil match days"],
    desc: "A Brazilian restaurant in Gowanus serving made-to-order caipirinhas and bottomless feijoada when Brazil plays, with a large projection screen.",
    review: "This large, airy Brazilian restaurant in Gowanus is one of the best places to watch a game: amazing food, good drinks, big-screen TV.",
    reviewSource: "Hudson River Blue",
  },
  {
    name: "Carragher's Pub & Restaurant",
    address: "17 John St, Financial District, Manhattan",
    borough: "Manhattan", neighborhood: "Financial District", team: "Open",
    tags: ["Multiple screens", "Liverpool FC official NYC bar", "Full food menu"],
    desc: "Official NYC bar for Liverpool FC, opened to all soccer fans for World Cup 2022 in the Financial District with a full menu.",
    review: "Carragher's is a dedicated soccer bar with a surprisingly solid beer menu. Show up early and grab a table with your crew.",
    reviewSource: "Matador Network",
  },
  {
    name: "Daly's Pub",
    address: "31-86 31st St, Astoria, Queens",
    borough: "Queens", neighborhood: "Astoria", team: "Open",
    tags: ["Fireplace", "Irish pub", "Croatia supporters destination"],
    desc: "A charming Irish pub in Astoria and a notable destination for Croatia supporters during World Cup 2022, steps from the N/W Broadway stop.",
    review: "This charming Irish pub in Astoria is actually a destination for Croatia fans. They have a fireplace, which pairs nicely with this tournament.",
    reviewSource: "Hudson River Blue",
  },
  {
    name: "Highbury Pub",
    address: "1002 Cortelyou Rd, Flatbush, Brooklyn",
    borough: "Brooklyn", neighborhood: "Park Slope", team: "Open",
    tags: ["All games including 5am", "World Cup 2022 HQ"],
    desc: "A Flatbush pub that showed every World Cup 2022 match including 5am kickoffs, self-declared World Cup 2022 HQ.",
    review: "They're showing all games, even the 5am ones. That's why they call themselves the 'World Cup 2022 HQ.'",
    reviewSource: "Hudson River Blue",
  },
  {
    name: "Bierhaus NYC",
    address: "712 3rd Ave, Midtown, Manhattan",
    borough: "Manhattan", neighborhood: "Midtown", team: "Germany",
    tags: ["Bavarian beer hall", "Spacious beer garden", "Beer boots", "Schnitzel + sausage"],
    desc: "A Bavarian-style beer hall broadcasting all World Cup 2022 matches in their spacious beer garden, particularly electric for Germany matches.",
    review: "This Bavarian-style beer hall may be rooting extra hard for Germany, but Bierhaus will be broadcasting all of the cup's soccer matches in their beer garden.",
    reviewSource: "6sqft, 2022",
  },
  {
    name: "Tampico NYC",
    address: "10 Delancey St, Lower East Side, Manhattan",
    borough: "Manhattan", neighborhood: "East Village", team: "Mexico",
    tags: ["8 TVs", "2 large projection screens", "Happy hour specials"],
    desc: "A Lower East Side Mexican bar that showed all World Cup 2022 group stage matches on 8 TVs and 2 large projection screens with happy hour specials.",
    review: "Tampico NYC showed all 2pm group stage games on its 8 TVs and 2 large projection screens with happy hour specials and discounted drafts.",
    reviewSource: "Fox 5 NY, 2022",
  },
]

export const TEAMS = [
  { name: "Argentina",    flag: "🇦🇷", conf: "CONMEBOL", color: "#0d47a1", bg: "#e3f2fd" },
  { name: "Australia",    flag: "🇦🇺", conf: "AFC",       color: "#4e342e", bg: "#efebe9" },
  { name: "Belgium",      flag: "🇧🇪", conf: "UEFA",      color: "#b71c1c", bg: "#ffebee" },
  { name: "Brazil",       flag: "🇧🇷", conf: "CONMEBOL", color: "#e65100", bg: "#fff8e1" },
  { name: "Cameroon",     flag: "🇨🇲", conf: "CAF",       color: "#1b5e20", bg: "#e8f5e9" },
  { name: "Canada",       flag: "🇨🇦", conf: "CONCACAF",  color: "#b71c1c", bg: "#ffebee" },
  { name: "Chile",        flag: "🇨🇱", conf: "CONMEBOL", color: "#c62828", bg: "#ffebee" },
  { name: "Colombia",     flag: "🇨🇴", conf: "CONMEBOL", color: "#bf360c", bg: "#fff3e0" },
  { name: "Costa Rica",   flag: "🇨🇷", conf: "CONCACAF",  color: "#1a237e", bg: "#e8eaf6" },
  { name: "Croatia",      flag: "🇭🇷", conf: "UEFA",      color: "#b71c1c", bg: "#ffebee" },
  { name: "Denmark",      flag: "🇩🇰", conf: "UEFA",      color: "#c62828", bg: "#ffebee" },
  { name: "Ecuador",      flag: "🇪🇨", conf: "CONMEBOL", color: "#f57f17", bg: "#fffde7" },
  { name: "Egypt",        flag: "🇪🇬", conf: "CAF",       color: "#b71c1c", bg: "#ffebee" },
  { name: "England",      flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", conf: "UEFA",      color: "#880e4f", bg: "#fce4ec" },
  { name: "France",       flag: "🇫🇷", conf: "UEFA",      color: "#1a237e", bg: "#e8eaf6" },
  { name: "Germany",      flag: "🇩🇪", conf: "UEFA",      color: "#37474f", bg: "#eceff1" },
  { name: "Ghana",        flag: "🇬🇭", conf: "CAF",       color: "#37474f", bg: "#eceff1" },
  { name: "Honduras",     flag: "🇭🇳", conf: "CONCACAF",  color: "#1565c0", bg: "#e3f2fd" },
  { name: "Hungary",      flag: "🇭🇺", conf: "UEFA",      color: "#b71c1c", bg: "#ffebee" },
  { name: "Iran",         flag: "🇮🇷", conf: "AFC",       color: "#1b5e20", bg: "#e8f5e9" },
  { name: "Italy",        flag: "🇮🇹", conf: "UEFA",      color: "#1565c0", bg: "#e3f2fd" },
  { name: "Ivory Coast",  flag: "🇨🇮", conf: "CAF",       color: "#e65100", bg: "#fff3e0" },
  { name: "Japan",        flag: "🇯🇵", conf: "AFC",       color: "#1565c0", bg: "#e3f2fd" },
  { name: "Mexico",       flag: "🇲🇽", conf: "CONCACAF",  color: "#1b5e20", bg: "#e8f5e9" },
  { name: "Morocco",      flag: "🇲🇦", conf: "CAF",       color: "#b71c1c", bg: "#ffebee" },
  { name: "Netherlands",  flag: "🇳🇱", conf: "UEFA",      color: "#e65100", bg: "#fff3e0" },
  { name: "New Zealand",  flag: "🇳🇿", conf: "OFC",       color: "#37474f", bg: "#eceff1" },
  { name: "Nigeria",      flag: "🇳🇬", conf: "CAF",       color: "#1b5e20", bg: "#e8f5e9" },
  { name: "Panama",       flag: "🇵🇦", conf: "CONCACAF",  color: "#b71c1c", bg: "#ffebee" },
  { name: "Paraguay",     flag: "🇵🇾", conf: "CONMEBOL", color: "#c62828", bg: "#ffebee" },
  { name: "Peru",         flag: "🇵🇪", conf: "CONMEBOL", color: "#b71c1c", bg: "#ffebee" },
  { name: "Poland",       flag: "🇵🇱", conf: "UEFA",      color: "#c62828", bg: "#ffebee" },
  { name: "Portugal",     flag: "🇵🇹", conf: "UEFA",      color: "#b71c1c", bg: "#ffebee" },
  { name: "Romania",      flag: "🇷🇴", conf: "UEFA",      color: "#e65100", bg: "#fff3e0" },
  { name: "Saudi Arabia", flag: "🇸🇦", conf: "AFC",       color: "#1b5e20", bg: "#e8f5e9" },
  { name: "Senegal",      flag: "🇸🇳", conf: "CAF",       color: "#1b5e20", bg: "#e8f5e9" },
  { name: "Serbia",       flag: "🇷🇸", conf: "UEFA",      color: "#c62828", bg: "#ffebee" },
  { name: "Slovenia",     flag: "🇸🇮", conf: "UEFA",      color: "#1565c0", bg: "#e3f2fd" },
  { name: "South Korea",  flag: "🇰🇷", conf: "AFC",       color: "#c62828", bg: "#ffebee" },
  { name: "Spain",        flag: "🇪🇸", conf: "UEFA",      color: "#b71c1c", bg: "#fff9c4"  },
  { name: "Switzerland",  flag: "🇨🇭", conf: "UEFA",      color: "#c62828", bg: "#ffebee" },
  { name: "Turkey",       flag: "🇹🇷", conf: "UEFA",      color: "#c62828", bg: "#ffebee" },
  { name: "Ukraine",      flag: "🇺🇦", conf: "UEFA",      color: "#1565c0", bg: "#e3f2fd" },
  { name: "Uruguay",      flag: "🇺🇾", conf: "CONMEBOL", color: "#1565c0", bg: "#e3f2fd" },
  { name: "USA",          flag: "🇺🇸", conf: "CONCACAF",  color: "#0d47a1", bg: "#e8eaf6" },
  { name: "Venezuela",    flag: "🇻🇪", conf: "CONMEBOL", color: "#c62828", bg: "#ffebee" },
]

export const GROUP_MATCHES = {
  Argentina:    [{ vs: "France",       date: "Jun 14", time: "3:00 PM",  venue: "MetLife Stadium, NJ" }, { vs: "Canada",      date: "Jun 17", time: "12:00 PM", venue: "TBD" },               { vs: "Group A TBD", date: "Jun 21", time: "TBD", venue: "TBD" }],
  Brazil:       [{ vs: "Morocco",      date: "Jun 14", time: "6:00 PM",  venue: "SoFi Stadium, LA"    }, { vs: "Germany",     date: "Jun 15", time: "12:00 PM", venue: "TBD" },               { vs: "Japan",       date: "Jun 18", time: "12:00 PM", venue: "TBD" }],
  Colombia:     [{ vs: "England",      date: "Jun 15", time: "3:00 PM",  venue: "MetLife Stadium, NJ" }, { vs: "Costa Rica",  date: "Jun 18", time: "6:00 PM",  venue: "TBD" },               { vs: "Group C TBD", date: "Jun 22", time: "TBD", venue: "TBD" }],
  USA:          [{ vs: "Honduras",     date: "Jun 15", time: "6:00 PM",  venue: "MetLife Stadium, NJ" }, { vs: "Mexico",      date: "Jun 16", time: "6:00 PM",  venue: "Rose Bowl, LA" },     { vs: "Group D TBD", date: "Jun 22", time: "TBD", venue: "TBD" }],
  Mexico:       [{ vs: "Ecuador",      date: "Jun 16", time: "12:00 PM", venue: "SoFi Stadium, LA"    }, { vs: "USA",         date: "Jun 16", time: "6:00 PM",  venue: "Rose Bowl, LA" },     { vs: "Group E TBD", date: "Jun 20", time: "TBD", venue: "TBD" }],
  England:      [{ vs: "Colombia",     date: "Jun 15", time: "3:00 PM",  venue: "MetLife Stadium, NJ" }, { vs: "Slovenia",    date: "Jun 17", time: "3:00 PM",  venue: "TBD" },               { vs: "Group C TBD", date: "Jun 21", time: "TBD", venue: "TBD" }],
  Portugal:     [{ vs: "Spain",        date: "Jun 16", time: "3:00 PM",  venue: "MetLife Stadium, NJ" }, { vs: "Group F TBD", date: "Jun 20", time: "TBD",     venue: "TBD" },               { vs: "Group F TBD", date: "Jun 24", time: "TBD", venue: "TBD" }],
  France:       [{ vs: "Argentina",    date: "Jun 14", time: "3:00 PM",  venue: "MetLife Stadium, NJ" }, { vs: "Group A TBD", date: "Jun 18", time: "TBD",     venue: "TBD" },               { vs: "Group A TBD", date: "Jun 22", time: "TBD", venue: "TBD" }],
  Germany:      [{ vs: "Brazil",       date: "Jun 15", time: "12:00 PM", venue: "TBD"                 }, { vs: "Australia",   date: "Jun 18", time: "3:00 PM",  venue: "TBD" },               { vs: "Group B TBD", date: "Jun 22", time: "TBD", venue: "TBD" }],
  Spain:        [{ vs: "Portugal",     date: "Jun 16", time: "3:00 PM",  venue: "MetLife Stadium, NJ" }, { vs: "Group F TBD", date: "Jun 20", time: "TBD",     venue: "TBD" },               { vs: "Group F TBD", date: "Jun 24", time: "TBD", venue: "TBD" }],
  Morocco:      [{ vs: "Brazil",       date: "Jun 14", time: "6:00 PM",  venue: "SoFi Stadium, LA"    }, { vs: "Group B TBD", date: "Jun 18", time: "TBD",     venue: "TBD" },               { vs: "Group B TBD", date: "Jun 22", time: "TBD", venue: "TBD" }],
  Canada:       [{ vs: "Argentina",    date: "Jun 17", time: "12:00 PM", venue: "TBD"                 }, { vs: "Group A TBD", date: "Jun 21", time: "TBD",     venue: "TBD" },               { vs: "Group A TBD", date: "Jun 25", time: "TBD", venue: "TBD" }],
  Ecuador:      [{ vs: "Mexico",       date: "Jun 16", time: "12:00 PM", venue: "SoFi Stadium, LA"    }, { vs: "Group E TBD", date: "Jun 20", time: "TBD",     venue: "TBD" },               { vs: "Group E TBD", date: "Jun 24", time: "TBD", venue: "TBD" }],
  Honduras:     [{ vs: "USA",          date: "Jun 15", time: "6:00 PM",  venue: "MetLife Stadium, NJ" }, { vs: "Group D TBD", date: "Jun 19", time: "TBD",     venue: "TBD" },               { vs: "Group D TBD", date: "Jun 23", time: "TBD", venue: "TBD" }],
  Japan:        [{ vs: "Brazil",       date: "Jun 18", time: "12:00 PM", venue: "TBD"                 }, { vs: "Group B TBD", date: "Jun 22", time: "TBD",     venue: "TBD" },               { vs: "Group B TBD", date: "Jun 26", time: "TBD", venue: "TBD" }],
  Australia:    [{ vs: "Germany",      date: "Jun 18", time: "3:00 PM",  venue: "TBD"                 }, { vs: "Group B TBD", date: "Jun 22", time: "TBD",     venue: "TBD" },               { vs: "Group B TBD", date: "Jun 26", time: "TBD", venue: "TBD" }],
  Slovenia:     [{ vs: "England",      date: "Jun 17", time: "3:00 PM",  venue: "TBD"                 }, { vs: "Group C TBD", date: "Jun 21", time: "TBD",     venue: "TBD" },               { vs: "Group C TBD", date: "Jun 25", time: "TBD", venue: "TBD" }],
  "Costa Rica": [{ vs: "Colombia",     date: "Jun 18", time: "6:00 PM",  venue: "TBD"                 }, { vs: "Group C TBD", date: "Jun 22", time: "TBD",     venue: "TBD" },               { vs: "Group C TBD", date: "Jun 26", time: "TBD", venue: "TBD" }],
}

export const TEAM_COLORS = {
  Argentina: { bg: "#e3f2fd", color: "#0d47a1" },
  Brazil:    { bg: "#fff8e1", color: "#e65100" },
  Colombia:  { bg: "#fff3e0", color: "#bf360c" },
  Mexico:    { bg: "#e8f5e9", color: "#1b5e20" },
  USA:       { bg: "#e8eaf6", color: "#0d47a1" },
  England:   { bg: "#fce4ec", color: "#880e4f" },
  Portugal:  { bg: "#ffebee", color: "#b71c1c" },
  Germany:   { bg: "#eceff1", color: "#37474f" },
  Spain:     { bg: "#fff9c4", color: "#795548" },
  Open:      { bg: "#f3e5f5", color: "#4a148c" },
}
